### ISSUE TITLE
problems with this code

### ISSUE THREAD

**Issue by colinpaicemq** [zedsec390/NJElib#7]
Ive experienced several problems with this code.  For example in the area of "to_bytes" where it needs to_bytes(.."big")
I have an updated version if you are interested.

**Comment by bigendiansmalls** [comment]
Most definitely interested, Colin. Thank you!  We definitely haven't traversed all the edge caes or use cases at all, so feel free to propose anything you think might fix an issue.  One of the things though is that the to_bytes func changed in python3.12 which is what I've been developing in. I know previous versions required the endianness.

see:
https://github.com/python/cpython/issues/89318
and
https://docs.python.org/3/whatsnew/changelog.html

I didn't make it backwards compatible with 3.10. Have you tried both to verify the issues? 

Either way, if you have fixes you'd like to see - fee free to shoot a PR over. Thank you!

**Comment by colinpaicemq** [comment]
Hi,

Thanks for you reply.  I'm on Python 3.10.12

Where  your version has
'NMRLEVEL' : int.to_bytes(d[1] & 0xF0),

I have
'NMRLEVEL' : (d[1] & 0xF0). to_bytes(1,"big"),

I looked at replacing to_bytes with my_to_bytes, and having logic within
the function depending on the version.  Similarly with from_bytes.

________________________________


def disconnect(self):
"""Close the connection."""
self.msg("Disconnecting")
sock = self.sock
self.sequence = 0x80 #reset sequence
self.connected = False
# are the following statements in the wrong order?
self.sock = 0
if sock:
sock.close()

See my comment
________________________

If I have

Reply = nje.sendCommand("$DLINE1")
print (Reply)
nje.set_debuglevel(1)
Reply = nje.sendCommand("$DNODE50")
print (Reply)

The second sendCommand is ignored.

It looks like
def sendMessage(self, message, user=''):
msg = "Sending Message: " + message
if user:
msg += " to user " + user.upper()
self.msg(msg)
msg = self.sendNMR(message, False, user)
time.sleep(5)
self.signoff()


does a signoff ... after sending one command
____________________________________


ef signoff(self):
#Sends a B Record
adios = (b'\x00\x00\x00\x19\x00\x00\x00\x00\x00\x00\x00\x09\x10\x02' +
self.sequence.to_bytes(1,"big") +
b'\x8F\xCF\xF0\xC2\x00\x00\x00\x00\x00\x00' )
# The following tries to send an int with value 0 ...!
#self.msg("Sending Signoff Record:
{0}".format(self.EbcdicToAscii(adios[18])))
self.sendData(adios)
self.disconnect()

The
self.EbcdicToAscii(adios[18]))


passes an integer with value(0).. and this fails to print.

That's all so far.


I came to this tool because someone asked me about AT-TLS ( SSL/TLS) and
NJE.   That is where I'm really interested in

Colin

**Comment by colinpaicemq** [comment]
Hi,

Attached is my njelib.py with a "fix" for  the to_bytes and from_bytes.
I've made a function which does the work, and any release specific changes
can go in there.
I've also included some TLS stuff, so you can specify a cert file, key
file, and a ca file

To use the TLS stuff you issue
import njelib
import sys
nje = njelib.NJE("N50","S0W1")
nje.set_debuglevel(1)


*nje.setTLS(certfile="/home/colinpaice/ssl/ssl2/jun24/docec521june.pem",
       keyfile="/home/colinpaice/ssl/ssl2/jun24/docec521june.key.pem",
     cafile="/home/colinpaice/ssl/ssl2/jun24/docca256.pem")*
*...*


I haven't used git hub with someone else's repository, so if there is a
better way of giving you the updates, please let me know.

Colin

**Comment by bigendiansmalls** [comment]
Hi Colin!

Thank you for doing all this. I could pull it in myself, but if you're keen to learn, here is how you would propose this formally (this would apply to any open source repository that you wanted to contribute to, generally) I don't know how much of this you know so apologies if it is remedial:

1) Fork our original repo to your github.
2) Clone that newly forked NJELIB repo from _your_ github to your local machine (git clone ... etc)
3) create a new branch on your local machine like (git checkout -b <newbranch>) 
4) within that new branch make your changes directly to the files so they work as you want them to.
5) add and commit your changes, then git push that branch back up to your github account
6) from within your github account, you should see something like this (an example from my personal repo, remember this is being done on your accont):
<img width="960" alt="image" src="https://github.com/zedsec390/NJElib/assets/13771080/57952673-2a18-430b-b25c-01d4e8bf0024">
7) click that "Compare & Pull Request" button
8) On the next page, in the description box - add and appropriate title + a good detailed description (like your issue post) of what you fixed and how
9) click "Create Pull Request" 

That's it for you.  What happens next is I get notified of a "pull request", I can download and merge and test your changes in a separate branch on my machine. Once tested I can either: merge it into main and then it's a part of the repo (with the logs showing the PR and who submitted it etc) or make tweaks to it then merge it or kick it back to you rejected or asking for changes etc.  Then we can iterate (probably this one would just get merged by me once i test it).

Does that make sense?  Feel free to reach out if that's too much or doesn't make sense.

Cheers
